### ISSUE TITLE
Audio Choppy with Browser Sources

### ISSUE THREAD

**Issue by gnkidwell** [obsproject/obs-browser#383] opened 2022-11-18 22:05 UTC
### Operating System Info

Windows 11

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/-qmo_pH7WcEkZrqs

### Expected Behavior

I use Control Audio via OBS exclusively to separate all of my audio sources into a audio slider in OBS. This has been successful in the past with being able to exclusively control all of my audio sources separately. 

### Current Behavior

The issue right now appears to be any Browser Source that has Control Audio via OBS selected. I run Triggerfyre, StreamElements, and StreamLabs browser sources for different audio related purposes in my streams. However, only when Control Audio via OBS is selected in these browser sources, does the audio become choppy and crackle.

### Steps to Reproduce

1. Create a new browser source
2. Go to the properties of the browser source and check Control Audio via OBS
3. Allow a browser source to play
...

### Anything else we should know?

I remember having some issues in OBS 27, but not to this extent, it is now constant and consistent once a browser source starts to play audio. However, if the box "Control Audio via OBS" is unchecked this behavior does not occur. I have even tried to set a constant frame rate in these sources, and the only issue here is with Control Audio via OBS in browser sources.

**Comment by Fenrirthviti** [comment] 2022-11-18 22:42
Duplicate of https://github.com/obsproject/obs-studio/issues/6612

**Closed by Fenrirthviti** 2022-11-18 22:42 UTC
