### ISSUE TITLE
cracking Audio using control Audio over OBS on a Browsersource

### ISSUE THREAD

**Issue by Svenja001** [obsproject/obs-browser#405] opened 2023-04-22 20:28 UTC
### Operating System Info

Windows 11

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/4Ktx2ybr5AMUGdyB

### Expected Behavior

Audio plays properly

### Current Behavior

Audio cracks when playing a Sound

### Steps to Reproduce

1. add a Browsersource from the Dashboard of soundalerts.com
2. In Advanced Audiosettings enable "Control Audio over OBS" and enable monitor and Output
3. configure a Sound that can be played with Channelpoints
4. while editing the Sound on the Soundalerts Dashboard, click "test in BrowserSource" until the Issue ocurs
...

### Anything else we should know?

here is the Recording I made to create the Log https://www.dropbox.com/s/agj7zlmnlytd7lv/2023-04-22%2022-08-46.mkv?dl=0
It also can happen with my Streamelements Browsersource, but that is not so reliable reproducable like it was with the Soundalerts Source today.

**Comment by Fenrirthviti** [comment] 2023-04-22 20:46
Duplicate of https://github.com/obsproject/obs-studio/issues/6612

**Closed by Fenrirthviti** 2023-04-22 20:46 UTC
