### ISSUE TITLE
Browser ignores video autoplay

### ISSUE THREAD

**Issue by delongerr** [obsproject/obs-browser#182] opened 2019-11-22 14:16 UTC
## Expected Behavior
Browser doesn't ignore video autoplay

## Current Behavior
Browser ignores video autoplay

## Steps to Reproduce
1. [Download](https://drive.google.com/file/d/1Sa_3G16kOd8FtyUB6qfcsUHuxajEsZex/view?usp=sharing) and unzip archive widget.zip
2. Open OBS
3. Click on "Plus" in sources and select "Browser"
4. Click "OK"
5. Set checkbox "Local file"
6. Browse our widget (widget/index.html)
7. Click "OK"

## Additional information
OBS v24.0.2
macOS 10.14.6

**Comment by phillipseamore** [comment] 2019-11-22 21:47
Try starting obs with the command line flag:
--autoplay-policy=no-user-gesture-required

Example on Win64:
obs64.exe --autoplay-policy=no-user-gesture-required

**Comment by delongerr** [comment] 2019-12-14 15:36
> Try starting obs with the command line flag:
> --autoplay-policy=no-user-gesture-required
> 
> Example on Win64:
> obs64.exe --autoplay-policy=no-user-gesture-required

This does not solve the problem for the users. I can run OBS with command line flag as developer widgets.

**Comment by WizardCM** [comment] 2019-12-27 23:37
Any objections to having this flag by default on browser _sources_? As brwoser sources aren't designed to be interacted with primarily. Though I worry this may break existing setups.

**Comment by Lange** [comment] 2019-12-27 23:39
@WizardCM I thought this was already added? https://github.com/obsproject/obs-browser/issues/105

**Comment by WizardCM** [comment] 2019-12-27 23:40
Ah, you're right. I'm blind! Closing.

**Comment by WizardCM** [comment] 2019-12-27 23:43
Actually, as this issue was created after the flag was added, I'm leaving this open for now.

**Comment by MattBroach** [comment] 2020-01-03 20:30
I can confirm the issue -- Same OBS and MacOS version as original poster.  As a test, I reverted to OBS 23.2.1, and the autoplay seemed to work.  I was, however, unable to get it to work using the `--autoplay-policy=no-user-gesture-required` flags on OBS 24.0.2

**Comment by bkeeneykid** [comment] 2020-07-11 22:38
I'd like to bump this again at this point saying I do have this issue as well. I'm on Arch Linux running OBS 25.0.7.r372 from git. On this same laptop, the video in question plays just fine on windows, however it does not play on Linux and seems to almost be transparent. On linux this is using CEF minimal version 3770.

**Comment by MorningStarGG** [comment] 2021-02-03 17:34
I am also not having any luck getting videos on browser web sources to autoplay. Help please?

**Comment by RytoEX** [comment] 2021-04-03 16:53
The file in the initial comment is no longer available.  Can someone else provide a reproducible test case?

**Comment by MadWolfDynamite** [comment] 2021-04-03 17:59
The steps for this issue should be reproduceable with this [Download](https://drive.google.com/file/d/1_6gDFdP8i3xFjts4DNJ8At_PDZzc-Im-/view?usp=sharing)
The only difference will be step 6 where you'll be browsing to `widget.html` instead of `widget/index.html`

**Comment by RytoEX** [comment] 2021-04-06 01:07
> 
> 
> The steps for this issue should be reproduceable with this [Download](https://drive.google.com/file/d/1_6gDFdP8i3xFjts4DNJ8At_PDZzc-Im-/view?usp=sharing)
> The only difference will be step 6 where you'll be browsing to `widget.html` instead of `widget/index.html`

Since #282 reported this on Windows, and I missed that this was originally reported on macOS, I tested this on Windows.  After some investigation, I believe this is related to hardware acceleration.

When I add this file as a browser source in OBS Studio 26.1.1 64-bit on Windows 10, the video autoplays for me instantly without interacting.  However, the video does seem to struggle to play smoothly in 27.0.0-rc1 unless you're interacting with the source.  When interacting, the video plays smoothly.  When not interacting, it sometimes plays a few frames here and there.  It works fine when I rebuild 27.0.0-rc1 with shared textures enabled.

We didn't enable hardware acceleration for browser sources on macOS until OBS Studio 26.1.2.  We believe that recent reports regarding seeing this behavior on 27.0.0-rc1 are due to a misconfiguration in that release that disabled hardware acceleration, and that will be fixed in future releases.

This behavior should go away if testing on macOS with OBS Studio 26.1.2 or OBS Studio 27.0.0-rc2 whenever that is released.

**Comment by RytoEX** [comment] 2021-04-11 01:58
It looks like while this and #282 exhibit the same behavior and they share the same underlying cause (disabled hardware acceleration), the immediate cause of each Issue is slightly different.

This issue was because hardware acceleration for browser sources was not enabled on macOS until OBS Studio 26.1.2.  This issue was reported against OBS Studio 24.0.2 on macOS, so hardware acceleration was not available.  This specific issue should be resolved as of OBS Studio 26.1.2.

#282 was reported against OBS Studio 27.0.0-rc1 on Windows 10.  Due to a configuration error during the build process, 27.0.0-rc1 was built without hardware acceleration support for the browser source.  That specific issue should be resolved with OBS Studio 27.0.0-rc2 when that is released.

With that said, I'm going to close this issue since it should have been fixed in OBS Studio 26.1.2.  I'm going to reopen #282 and target it to be fixed in OBS Studio 27.0.0-rc2.  Sorry for the trouble with shifting issues around, and sorry for the noise.

**Closed by RytoEX** 2021-04-11 01:58 UTC
Labels: Seeking Testers
