### ISSUE TITLE
Browser Source ignores video autoplay unless interacted with

### ISSUE THREAD

**Issue by MadWolfDynamite** [obsproject/obs-browser#282] opened 2021-04-03 09:36 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/LWWCcT-OjjcB0dmh

### Expected Behavior

When browser source is active any video tags with autoplay attribute will playback

### Current Behavior

Video appears paused until source is manually interacted with via the means of interact popup. Even then, mouse has to be constantly moved to properly show playback

### Steps to Reproduce

1. Create a html page with <Video> tag that includes "autoplay muted" attributes
2. Add browser source linking to html page to any scene
3. Select browser source and clink on "Interact"
4. Move cursor back and forth within the window that appears
4a. Open html file in any web browser compatible with <video> tag

### Anything else we should know?

This was only tested with a local file, but URLs may also be affected by this.
The steps for this issue should be reproduceable with this [Download](https://drive.google.com/file/d/1_6gDFdP8i3xFjts4DNJ8At_PDZzc-Im-/view?usp=sharing).

**Comment by RytoEX** [comment] 2021-04-11 01:58
It looks like while this and #182 exhibit the same behavior and they share the same underlying cause (disabled hardware acceleration), the immediate cause of each Issue is slightly different.

#182 was because hardware acceleration for browser sources was not enabled on macOS until OBS Studio 26.1.2.  That issue was reported against OBS Studio 24.0.2 on macOS, so hardware acceleration was not available.  That specific issue should be resolved as of OBS Studio 26.1.2.

This issue was reported against OBS Studio 27.0.0-rc1 on Windows 10.  Due to a configuration error during the build process, 27.0.0-rc1 was built without hardware acceleration support for the browser source.  This specific issue should be resolved with OBS Studio 27.0.0-rc2 when that is released.

With that said, I'm going to close #182 since it should have been fixed in OBS Studio 26.1.2.  I'm going to reopen this and target it to be fixed in OBS Studio 27.0.0-rc2.  Sorry for the trouble with shifting issues around, and sorry for the noise.

**Comment by RytoEX** [comment] 2021-04-13 00:43
@MadWolfDynamite Can you please verify that this is fixed in OBS Studio 27.0.0-rc2?

**Comment by RytoEX** [comment] 2021-04-15 07:32
I've verified that the test case now exhibits the Expected Behavior in OBS Studio 27.0.0-rc2 on Windows 10, so I'm going to close this issue.

**Closed by RytoEX** 2021-04-15 07:32 UTC
