### ISSUE TITLE
Request: Volume Control for obs-browser

### ISSUE THREAD

**Issue by LevantinLynx** [obsproject/obs-browser#11] opened 2016-01-25 00:45 UTC
Currently there is no way to mute sounds from pages.
Additional if one uses the browser to embed twitchalerts (with sound) on multiple scenes they all play on event trigger.

**Comment by Gol-D-Ace** [comment] 2016-03-06 13:37
You can unload the browser source when it's not showing.
![06-03-2016_14 37 20](https://cloud.githubusercontent.com/assets/5058319/13554479/ff1b4aae-e3a8-11e5-9bf2-f4e5b67e185f.png)

**Comment by LevantinLynx** [comment] 2016-03-08 10:32
Thanks Gol-D-Ace,
well this solves my immediate problem, will leave the request open 'cause it still would be very nice to be able to change the volume of a browser source.

**Comment by OsirisNL** [comment] 2016-03-08 11:23
Unfortunately until CEF supports that kind of handling of audio, that won't happen.

**Comment by jnovack** [comment] 2016-04-25 16:01
Would this mean adding an "audio source" in the panel for this individual browser source instance (in the event I had multiple browser sources instances)?

**Comment by LevantinLynx** [comment] 2016-04-25 16:34
That was exactly what i would like to see. Individual volume controls per browser source instance in the scene. Given that it's supported ofc.

**Comment by jp9000** [comment] 2016-04-25 18:46
Different volume per scene item (rather than per source) is basically implemented internally but hasn't been put in to the main UI.  The question is how to implement something like that in to the user interface in a way in which wouldn't be confusing or convoluted to most casual users.

**Comment by OsirisNL** [comment] 2016-04-25 21:44
But first CEF needs to support it.

**Comment by jp9000** [comment] 2016-04-25 21:45
CEF itself?  I think it does.  I know people have accomplished it elsewhere.  I could be totally crazy though.

**Comment by dodgepong** [comment] 2016-04-25 21:45
I know that vMix found a way to do it, somehow.

**Comment by jnovack** [comment] 2016-04-25 21:53
> The question is how to implement something like that in to the user interface in a way in which wouldn't be confusing or convoluted to most casual users.

I just imagined that "Source Name" would show up in **Mixer** when the scene was selected, just like media sources do now.

**Comment by OsirisNL** [comment] 2016-04-25 21:54
The CEF docs don't seem to reference anything related to audio.

**Comment by jp9000** [comment] 2016-04-25 22:47
Ah, maybe it was a specific audio-related patch someone did.  I really need to make time to contribute to the plugin.

**Comment by OsirisNL** [comment] 2016-04-26 06:58
Perhaps you saw this? https://bitbucket.org/chromiumembedded/cef/pull-requests/18/adding-audio-support/

**Comment by CoDEmanX** [comment] 2016-09-06 11:31
> jp9000: Different volume per scene item (rather than per source) is basically implemented internally but hasn't been put in to the main UI. The question is how to implement something like that in to the user interface in a way in which wouldn't be confusing or convoluted to most casual users.

Maybe there should really be two modes of operation, basic and advanced? My first idea was to separate studio mode and basic mode stronger, but on second thought that is probably not a good idea as you still may want the "staging" area to reconfigure your scenes during streaming/recording but otherwise want to use just basic functionality of OBS.

Advanced audio routing/control could be part of an "advanced" mode, with more knobs and shebang if you know what you are doing.

**Comment by langel** [comment] 2017-08-19 21:40
Putting a simple Volume input in the properties window with a value range of 0-100 would make me really happy. More specifically, I don't understand why you can hear a browser source if it's not in your current scene.

**Comment by dthpth** [comment] 2019-01-09 23:56
Since CEF on the way to add necessary (I guess?) changes at https://bitbucket.org/chromiumembedded/cef/pull-requests/177/add-ability-to-capture-audio-output-to
Are you planning to review this and implement separate audio sources for the Browser?

Btw, my use case: do not include audio playing in the one of browsers into the stream record file but keep it on the live stream.

**Comment by WizardCM** [comment] 2019-01-10 00:08
Thanks for bringing this particular issue number to my attention.

There is now a browser source branch [here](https://github.com/obsproject/obs-browser/tree/audio_support) (audio_support) which adds this capability. It will require testing, however **it won't get merged to master until both CEF PRs have been reviewed and are confirmed to be merged with CEF**. This is in case they change, as we want something relatively stable before we include it in OBS.

> Relies on two cef PR:
177 : Add ability to capture audio output to buffer via cef handler
173 : Mute audio in the browser (issue #1806)
> 
> The audio from browser source is now muted to desktop.
It can be captured and monitored.
The PR is compatible with multiple audio sources in same browser page. 

![Animation of browser volume meter](https://cdn.discordapp.com/attachments/398528383266586627/530526886279774227/2019-01-03_15-24-07.gif)

**Comment by dragonbane0** [comment] 2019-02-10 00:20
This is literally essential for us and until now we had to re-route OBS's whole output audio to itself via hacky means to control the browser audio which is quite unstable. Thank you for getting this drafted up so quick with the CEF PR's on the horizon!

**Comment by WizardCM** [comment] 2019-02-10 00:42
Latest update: "Add ability to capture audio output to buffer via cef handler" has been tested by Marshall of CEF and it's looking very promising (could be merged soon). "Mute audio in the browser" has been resubmitted to ensure it covers all of Marshall's concerns, but it's looking like that one will be merged too.

These changes should not be expected in OBS v23 (RC came out today), but we're keeping a very close eye on this for a future version of OBS.

**Comment by RytoEX** [comment] 2019-02-10 00:45
@WizardCM @DDRBoxman 
Following up with some links, [CEF PR 173](https://bitbucket.org/chromiumembedded/cef/pull-requests/173/mute-audio-in-the-browser-issue-1806/diff) has been superseded by [CEF PR 195](https://bitbucket.org/chromiumembedded/cef/pull-requests/195/mute-audio-in-the-browser-issue-1806/diff).

[CEF PR 177](https://bitbucket.org/chromiumembedded/cef/pull-requests/177/add-ability-to-capture-audio-output-to/diff) currently looks like it will be merged into CEF 3683, though that may change.  CEF PR 177 is undergoing some last minute changes at the moment.

**Comment by dragonbane0** [comment] 2019-02-25 22:46
Looks like both PRs are about to get merged which is promising

**Comment by dragonbane0** [comment] 2019-03-14 03:24
CEF Branch 3683 now has both relevant PRs merged in: https://bitbucket.org/chromiumembedded/cef/branch/3683

**Comment by WizardCM** [comment] 2019-03-14 22:24
PR #157 has been submitted.

**Comment by flyinpingwin** [comment] 2019-04-14 04:54
SOLUTION!! sooo alot simpler than what yall are making it. Go to windows volume mixer and turn down OBS volume, it turns down the output volume of the browser for both your viewers and yourself! :D hope this helped

**Comment by WizardCM** [comment] 2019-12-27 22:43
Whoops, looks like we forgot to close this ticket once we merged and released this capability! If you haven't already, update to OBS Studio v24.0.x :)

**Closed by WizardCM** 2019-12-27 22:43 UTC
Labels: Waiting on CEF upstream
