### ISSUE TITLE
[BUG] Memory constantly increasing and never clearing out when using CSS animation

### ISSUE THREAD

**Issue by njutn95** [obsproject/obs-browser#223] opened 2020-04-21 21:07 UTC
## Platform
Operating system and version: `Windows 10`
OBS Studio version: `25.0.4 (64 bit)`

## Expected Behavior
Page with static content should have steady (or nearly as steady) RAM usage. I'm not sure how browsers handle CSS animations, but I believe they're not really supposed to be constantly grabbing new memory (and not releasing old one), but I may be wrong.

## Current Behavior
If page is running for 2 or more minutes (with only one animation and no other code), `obs-browser-page` process starts grabbing 4 KB of RAM every 1-2 seconds. If left running for ours, memory keeps increasing and is never released. If page without animation is opened then RAM usage is almost the same as it was when first opened (slight difference, sometimes higher sometimes lower, I guess browser is doing some other things in the background that's causing the small difference). 

## Steps to Reproduce

Save the file as `*.html` and open it inside OBS

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        div {
            display: flex;
            justify-content: center;
            align-items: center;
            width: 100vw;
            height: 100vh;
        }
        
        span {
            background-color: red;
            display: block;
            width: 50px;
            text-align: center;
            transform: scale(1);
            animation: scaling 2s ease-in-out infinite alternate;
        }

        @keyframes scaling {
            0% {
                transform: scale(0.9);
            }
            100% {
                transform: scale(5);
            }
        }
    </style>
</head>
<body>
<div>
    <span>Text</span>
</div>
</body>
</html>
```

Video proof: https://www.screencast.com/t/baVhjUp8Ani

## Additional information
Memory increase is happening with both preview on and off, it doesn't make the difference as seen on the video. If you need any more information, do let me know.

**Comment by Fenrirthviti** [comment] 2020-04-21 21:08
Dupe of #221

**Closed by Fenrirthviti** 2020-04-21 21:08 UTC
