### ISSUE TITLE
Build breaks on aarch64: invalid conversion between vector type and integer type

### ISSUE THREAD

**Issue by yurivict** [obsproject/obs-browser#242] opened 2020-09-19 21:04 UTC
I don't have log, someone else placed this BROKEN label into the FreeBSD port ```multimedia/obs-studio```.

**Comment by notr1ch** [comment] 2020-09-19 21:08
This is not helpful without knowing the affected source file. Are you sure it involves obs-browser?

**Comment by yurivict** [comment] 2020-09-19 21:18
The BROKEN_aarch64 has been there for 2+ years. I removed it and asked to post the log here in case it still breaks on aarch64.

**Comment by WizardCM** [comment] 2021-01-09 06:13
Closing due to lack of context, information & reproduction steps.

**Closed by WizardCM** 2021-01-09 06:13 UTC
