### ISSUE TITLE
obs-browser does not expose method to obtain active status before events are fired

### ISSUE THREAD

**Issue by Xaroth** [obsproject/obs-browser#255] opened 2020-12-09 15:26 UTC
## Platform

Operating system and version: Not OS-dependent
OBS Studio version: master

## Current Behavior
When the browser context is created, and the page is loaded, the obs-browser source exposes various bits of information, either via the JS API, or via other properties that can be accessed via JS (like the document visibility marker). One exception to this is the active status of the source. From what I can see (and what is documented), the only way of seeing this information during events being fired, however, if the scene is already active while the context is being created, there is no way of knowing that the source is active.

## Additional information

The JS API exposes the following bits of information through events:
- Recorder status
- Replay buffer status
- Streaming output status
- Current scene info (name, height, width)
- Visibility status (Whether we're part of a visible scene)
- Active status (Whether we're part of an active scene)

Outside events, the following information can be obtained:

#### Visibility status

During [BrowserApp::OnContextCreated](https://github.com/obsproject/obs-browser/blob/666ca9db454f558385098d43696149b080b184ca/browser-app.cpp#L108), [SetDocumentVisibility](https://github.com/obsproject/obs-browser/blob/666ca9db454f558385098d43696149b080b184ca/browser-app.cpp#L141) is triggered to ensure that the `document.visibility` (on all frames) is set to either `"visible"` or `"hidden"`.
While this is not an ideal bool you can test with directly, it having only two values makes it usable.

#### Recorder/Replay/Streaming status

One can use `window.obsstudio.getStatus()` to obtain the current status for the recorder, replay buffer and streaming output. 

#### Scene information

`window.obsstudio.getCurrentScene()` can be used to obtain the scene information.

## Suggested fix

I would suggest updating `window.obsstudio.getStatus` to also include the `visible` and `active` status. this ensures that both properties are directly available from obs-browser through a callback, without having to parse visibility status.

**Comment by dkonopka** [comment] 2021-02-26 14:51
@Xaroth this is exactly what I'm missing in the current API, it would be awesome to see it implemented 🚀 🚀 🚀

**Comment by SReject** [comment] 2021-03-03 14:07
I need this functionality as well for [obsstudio.js](https://github.com/SReject/obsstudio.js)

**Comment by gxalpha** [comment] 2021-06-18 11:06
I think this is solvable pretty easily if #281 is merged, I’ll look into this after that happens

**Comment by dkonopka** [comment] 2021-06-29 14:13
@gxalpha great to read that, fingers crossed then, can't wait! 💪

**Comment by dkonopka** [comment] 2021-09-14 10:55
@gxalpha so after merged #281 how do you see such a feature is it possible to implement it soon?

**Comment by mols1980** [comment] 2021-12-27 02:31
lots to learn especially i am not even began

**Comment by dkonopka** [comment] 2022-01-04 23:37
@gxalpha any chances to work on this in the upcoming weeks? :)

**Comment by dkonopka** [comment] 2022-03-10 20:36
Because there are a lot of use-cases of this feature, I think it's really worth considering implementation of such functionality, OBS team, what do you think? :-)

**Comment by gxalpha** [comment] 2022-03-10 20:52
Feel free to implement it yourself and open a PR!

When asking others to add new features, please keep in mind there often are other features with higher priorities; and most people here do this in their free time.

Fyi, I haven't responded so far because I didn't notice, but I'm personally not planning to add this in the near future, mainly because of other priorities (including real life).

**Comment by dkonopka** [comment] 2022-03-20 07:04
@gxalpha thank you for your information, will try to do it on my own!

**Comment by dkonopka** [comment] 2022-05-31 07:02
@VodBox any updates on this, how do you it in terms of implementation?

**Comment by VodBox** [comment] 2022-06-04 02:40
> @VodBox any updates on this, how do you it in terms of implementation?

Not yet. This should be fairly simple, just some personal issues keeping it being done.

**Comment by dkonopka** [comment] 2022-06-16 18:43
@VodBox fingers crossed then! 💪

**Comment by dkonopka** [comment] 2022-07-25 07:42
@VodBox do you see any chances to finish this feature in this quarter?

**Comment by dkonopka** [comment] 2022-11-04 20:53
@WizardCM @VodBox any updates on this, even an estimation that you want to place it in roadmap in e.g. Q2 2023 will be helpful, thanks

**Comment by dkonopka** [comment] 2023-06-26 19:55
@WizardCM @VodBox i will try luck and ask again if this is even possible to put it in your roadmap for upcoming quarters :)?

**Comment by Fenrirthviti** [comment] 2023-06-26 20:19
VodBox has since moved on from contributing to the project in pursuit of their career, so they are no longer available to be working on this.

This really shouldn't be an open issue anymore, as it's a feature request and not a bug.

**Closed by Fenrirthviti** 2023-06-26 20:19 UTC
Labels: Good first issue
