### ISSUE TITLE
obs-browser FTBFS on Linux due to obs-browser-page target name existing as a directory

### ISSUE THREAD

**Issue by flexiondotorg** [obsproject/obs-browser#239] opened 2020-09-06 14:00 UTC
## Platform
  * Ubuntu 20.04
  * OBS Studio version: 26.0.0-rc1

## Expected Behavior
When `-DBUILD_BROWSER=TRUE` is enabled and a supported CEF is available, `obs-browser.so` should successfully build from source.

## Current Behavior
Enabling  `-DBUILD_BROWSER=TRUE` with a supported CEF available fails to build with the following error:

```
/usr/bin/ld: cannot open output file obs-browser-page: Is a directory
collect2: error: ld returned 1 exit status
make[2]: *** [plugins/obs-browser/CMakeFiles/obs-browser-page.dir/build.make:131: plugins/obs-browser/obs-browser-page] Error 1
make[1]: *** [CMakeFiles/Makefile2:1575: plugins/obs-browser/CMakeFiles/obs-browser-page.dir/all] Error 2
```

## Steps to Reproduce
```
cmake obs/src -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DUNIX_STRUCTURE=TRUE -DBUILD_BROWSER=TRUE -DCEF_ROOT_DIR=stage/CEF
```

## Additional information
I've only recently encountered the issue, following an upgrade of my build environment to Ubuntu 20.04 from 18.04. I think the significant change is moving from `cmake` 3.10 to `cmake` 3.16. Never the less, `cmake` is being instructed to build the target binary using the same name as a directory that already exists.

  * https://github.com/obsproject/obs-studio/issues/2490

**Comment by Fenrirthviti** [comment] 2020-09-07 06:46
This is building fine on my system on Ubuntu 18.04, can you provide more details on your build environment? I don't like the idea of changing the name here, it doesn't seem like the correct solution. Can you also test building v24 as mentioned in that linked issue which worked fine? We'll need to narrow down where this was introduced, and I am strongly against renaming the processes like this to avoid inconsistencies across the program.

**Comment by flexiondotorg** [comment] 2020-09-08 09:47
This change does not rename the process, the resulting binary is still called `obs-browser-page`. All that is renamed is the folder in which the source is located.

You won't encounter this issue on Ubuntu 18.04 with `cmake` 3.10. The build failure manifested with a newer `cmake`, which is 3.16 in 20.04. I currently maintain two builds of OBS:

  * OBS 25.0.0.8 built on Ubuntu 18.04 using `cmake` 3.10 and `gcc` 8.4.0
  * OBS 25.0.0-rc1 built on Ubuntu 20.04 using `cmake` 3.16 and  `gcc` 9.3.0

I apply this patch in both builds and both succeed. Both create the `obs-browser-page` binary and Browser sources work in OBS. Without this patch, the build on 20.04 fails. 

Even though browser sources were not supported on Linux with OBS 24, I have successfully compiled OBS 24 using the same patch and it generated `obs-browser-page` and `obs-browser.so`; although I can't test any functionality.

**Comment by Gol-D-Ace** [comment] 2020-09-08 09:57
This issue seems to be unique to your system.
It isn't happening on the PPA build bot for example.

https://launchpadlibrarian.net/495548180/buildlog_ubuntu-focal-amd64.obs-studio_26.0.0-rc1-0obsproject2~focal_BUILDING.txt.gz

**Comment by Gol-D-Ace** [comment] 2020-09-08 10:09
Also not happening on my local focal system.

**Comment by WizardCM** [comment] 2020-09-08 10:10
Not happening on my 20.04 builds either.

**Comment by Frigolit** [comment] 2021-03-06 07:16
I can replicate this on a Gentoo system as well using cmake 3.18.5 and gcc 9.3.0.

**Comment by RytoEX** [comment] 2024-07-25 21:29
As we were never able to reproduce the original report, and the build system has been so heavily changed from the time when this was reported, I'm going to close this.

**Closed by RytoEX** 2024-07-25 21:29 UTC
