### ISSUE TITLE
Idea: Sitemanipulation like Tampermonkey

### ISSUE THREAD

**Issue by danielengels** [obsproject/obs-browser#244] opened 2020-10-07 17:15 UTC
Would be a great feature, if u could inject some own javascript, to inject some code on the site you are with obs-browser plugin. so u can add some features like reacting on events and manipulation the orginal-side within obs, like it is down with custom css.
Tampermonkey https://www.tampermonkey.net/ for example is a chrome plugin (and for other browsers) give u an easy way to inject your own code to sites and change it. 
For example i am using tampermonkey to inject some code on a site, that i display in chome to connect to virtual camera that other can see it in zoom. But some features are not avaiable on the site and i want to visible disable some features.
At the moment i use chrome and a window recording, but i could do that in obs, that would be perfect.

**Comment by dodgepong** [comment] 2020-10-07 17:23
Duplicate of #87 

Also, ideas are better submitted on https://ideas.obsproject.com. This has already been submitted here: https://ideas.obsproject.com/posts/709/add-additional-javascript-for-browser-source

Lastly, there's already a pull request open to implement this, with quite a but of discussion around it regarding security concerns: https://github.com/obsproject/obs-browser/pull/137

**Closed by dodgepong** 2020-10-07 17:23 UTC

**Comment by danielengels** [comment] 2020-10-07 17:36
Thanks for your fast answer! Don't know the idea page. I will use that for other ideas and vote for the javscript idea ;)
I can understand the security concerns, if someone just copy some snippets... but hope someone will implement that soon!
