### ISSUE TITLE
Can't paste password into Youtube control panel 

### ISSUE THREAD

**Issue by snicolai** [obsproject/obs-browser#421] opened 2023-08-19 19:28 UTC
### Operating System Info

macOS 13

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/XcLiKuxYoUhhViKZ

### Expected Behavior

Paste should work in the Youtube control panel.

### Current Behavior

Unable to paste a password into the Youtube control panel.  

Pressing cmd-V does not paste.  

Paste is not available in the Edit menu.

### Steps to Reproduce

MacOS 13.5.1 (22G90) 

1.  Start up 30.0.0-beta2
2.  enter an email into the Youtube control panel
3.  Try to paste a password.
...

**Comment by RytoEX** [comment] 2023-08-19 19:35
Duplicate of #365

**Closed by RytoEX** 2023-08-19 19:35 UTC
