### ISSUE TITLE
Active browser source freezes entire macOS system on scene changes

### ISSUE THREAD

**Issue by PatTheMav** [obsproject/obs-browser#139] opened 2018-10-28 20:22 UTC
Running OBS 22.0.3 on macOS Mojave leads to whole-system freezes when a browser source scene is available in the currently active scene collection.

Freezes occur on:

* First launch of OBS (might be unrelated, freezes happen even without active browser source scene, but are made worse by it being available)
* After UI has been rendered and browser source is rendered for the first time
* Browsing through file selection dialogs
* Switching to scenes with an active browser source _from_ any other scene
* Switching a browser source scene to visible state from invisible
* Changing properties of the browser source

Freezes take anywhere from 5-10 seconds and block the whole OS (except for the mouse cursor).

Example log file: https://gist.github.com/PatTheMav/6a68c7ec2bbd8e43748cb532e0fc96a0

In the log file gist, the freeze occurs between switching to the "Broadcast" scene and the switch to the "Paused" scene: The system hangs for ~13 seconds before becoming response again and executing the switch.

**Comment by shawnbutts** [comment] 2018-11-03 20:07
i see this as well.  makes obs nearly unusable for me.

@PatTheMav do you see the freeze on the stream/recording or just in the streamers side?

**Comment by PatTheMav** [comment] 2018-11-03 22:02
Rendering is affected as well - the only ‘fix’ is to keep the scene-monitoring window open as this keeps the browser source active as well.

Without this switching to a scene with a browser source not only freezes the machine, but also freezes the stream.

**Comment by DDRBoxman** [comment] 2018-11-03 23:41
Mind posting what model mac you are running into this on?

I failed to replicate it on a 2013 Mac Pro and a 2017 Macbook Pro

**Comment by shawnbutts** [comment] 2018-11-03 23:54
MacBook Pro (Retina, 15-inch, Late 2013) running macOS 10.14
2.6 Ghz Intel Core i7
16 GB 1600 Mhz DDR3
Intel Iris Pro 1536 MB Graphics

**Comment by DDRBoxman** [comment] 2018-11-04 17:46
I'll give it a try on a few other models that are hanging around the office on Monday.

**Comment by PatTheMav** [comment] 2018-11-04 17:48
@DDRBoxman got it - will try to disable other plugins to rule out some incompatibility. Also if you have any other ideas what I could try, I'll be happy to hear them (e.g. if there are some debug switches that make OBS' logging more verbose).

**Comment by PatTheMav** [comment] 2018-11-04 23:30
Another behavior that I observed while testing:

* Sometimes the browser source disappears from preview (and rendered output) when switching to and from scenes with the source in it.
* When opening the properties window of the browser source, it is rendered in this window's preview screen and upon closing it, OBS freezes up again and the browser source becomes visible again
* When closing the properties window via `Cancel` nothing happens however
* The same applies if a scene is included as a source in another scene - the browser source disappears completely and can only be recovered by opening the properties window
* Toggling the visibility state of the browser source has no influence on this
* As long as the browser source is in this state, no freezes occur
* Enabling `Refresh browser when scene becomes active` has no effect

OBS log has no output besides the scene switches. The only fix for most issues seems to keep a multi-view window open, which - depending on the number of scenes - eats quite a lot of CPU on macOS, but the sources stay active and no freezes occur.

**Comment by DDRBoxman** [comment] 2018-11-05 17:38
Late 2013 iMac with a geforce card seems okay

I'd recommend running obs from the Instruments tool that ships with xcode and doing a time profiler recording.

**Comment by PatTheMav** [comment] 2018-11-05 23:46
@DDRBoxman Thanks - I cleaned my system of all traces of OBS (as far as I know at least) and reinstalled OBS without importing old profiles. But issue appears as soon as I add a browser source to a scene.

I haven't been able to replicate it on another MacBook Pro at work as well. Instruments shows the OBS process to be in the "spinning" state after a browser source becomes active, with functionality within the CEF taking up the most process time. Unfortunately I'm at the end of my wits with regards to debugging/profiling macOS apps.

**Comment by PatTheMav** [comment] 2018-11-06 22:30
@shawnbutts - quick question - does your Mac have an AMD or Intel GPU?

**Comment by shawnbutts** [comment] 2018-11-06 22:35
Intel and nvidia.  Details below.  I do force it to the discrete nvidia one when using obs. 


Intel Iris Pro:

  Chipset Model:	Intel Iris Pro
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel
  Device ID:	0x0d26
  Revision ID:	0x0008
  Automatic Graphics Switching:	Supported
  gMux Version:	4.0.8 [3.2.8]
  Metal:	Supported, feature set macOS GPUFamily1 v4



NVIDIA GeForce GT 750M:

  Chipset Model:	NVIDIA GeForce GT 750M
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x8
  VRAM (Dynamic, Max):	2048 MB
  Vendor:	NVIDIA (0x10de)
  Device ID:	0x0fe9
  Revision ID:	0x00a2
  ROM Revision:	3776
  Automatic Graphics Switching:	Supported
  gMux Version:	4.0.8 [3.2.8]
  Metal:	Supported, feature set macOS GPUFamily1 v4

**Comment by PatTheMav** [comment] 2018-11-06 22:39
So doesn't seem to be limited to a certain GPU type. The only other peculiarity I could find is a 5-10 second delay in the debug log between the browser source loading the initial URL and the first non-root source (e.g. a CSS or JS file from the `<head>` element). But I don't know if this is related to the actual web request or a "hang-up" inside CEF.

**Comment by PatTheMav** [comment] 2018-11-20 23:34
Quick update - I've did some more tests: OBS versions as far back as 19.0.3 freeze for a short time on launch (I've seen this happen on all Mac models available to me), and all versions up to 21.1.1 are "snappier" than the more recent versions.

The BrowserSource plugin still freezes a bit when it becomes active, but the freezes are much shorter than with later versions.

I'm inclined to believe this is an issue with CEF and macOS Mojave, as all tested versions worked fine on High Sierra on the same Macs before the update, or - maybe worse - another piece installed on the system that has issues with Mojave but exhibits its issues through the CEF inside OBS. Talking about a needle in a haystack.

I was also able to reproduce the bug of the browser source changing sizes on every scene change, but will investigate that one a bit more after my vacation.

**Comment by zikphil** [comment] 2018-12-26 04:57
> Quick update - I've did some more tests: OBS versions as far back as 19.0.3 freeze for a short time on launch (I've seen this happen on all Mac models available to me), and all versions up to 21.1.1 are "snappier" than the more recent versions.
> 
> The BrowserSource plugin still freezes a bit when it becomes active, but the freezes are much shorter than with later versions.
> 
> I'm inclined to believe this is an issue with CEF and macOS Mojave, as all tested versions worked fine on High Sierra on the same Macs before the update, or - maybe worse - another piece installed on the system that has issues with Mojave but exhibits its issues through the CEF inside OBS. Talking about a needle in a haystack.
> 
> I was also able to reproduce the bug of the browser source changing sizes on every scene change, but will investigate that one a bit more after my vacation.

Thank you so much for looking into this. This has been a major issue for me so far, everytime I open OBS my entire system freezes 1-2 seconds for every Browser Source I have in my scene. It is really painful.

**Comment by PatTheMav** [comment] 2019-02-18 21:15
@zikphil As I mentioned in my previous comment, this could very well be a CEF issue, as even older OBS versions exhibit this problem. Recently I had to re-install macOS in my iMac and the problem came back immediately.

I've been working with Apple developers on another issue with the particular AMD GPU (390 series) in my machine and they acknowledged it as an open issue with macOS Mojave that's being investigated.

If CEF is updated (I believe @DDRBoxman is waiting for an upstream update anyway), I will run some tests again, maybe a more recent CEF build fixes this.

**Comment by chrizstone** [comment] 2019-08-11 15:48
The issue is still present... If I make my browser source invisible, I have no problems. If its visible, OBS and MACOS are freezing when switching scenes... Any fix for this yet?

**Comment by dodgepong** [comment] 2019-08-11 16:30
@chrizstone What version of OBS are you on?

**Comment by chrizstone** [comment] 2019-08-11 16:40
@dodgepong 23.2.1

**Comment by chrizstone** [comment] 2019-09-28 08:30
No fix for this?

**Comment by PatTheMav** [comment] 2019-12-17 00:06
FWIW, most current macOS versions don't exhibit this issue anymore.

**Comment by WizardCM** [comment] 2019-12-27 22:56
Thanks for the update @PatTheMav - I'll close this issue for now in that case.

To others who ran into this issue, feel free to comment here if it still happens in 24.0.x for you. Be sure to mention which version of macOS you're running.

**Closed by WizardCM** 2019-12-27 22:56 UTC
