### ISSUE TITLE
Browser Source does not animate

### ISSUE THREAD

**Issue by ryanfreng** [obsproject/obs-browser#231] opened 2020-07-02 15:51 UTC
## Platform

macOS Catalina Version 10.15.5
OBS Studio 25.0.8 (64 bit)

## Expected Behavior

Browser sources should correctly animate the content from the website that it's rendering. I'm using a streamelements custom overlay.

## Current Behavior

The browser content animates for a few frames then freezes. 

## Steps to Reproduce

1. Add a browser source to a scene that has animation (https://drive.google.com/file/d/1o9gUDd11w2x5qzzvml7IVrYFLvXYqoVr/view?usp=sharing)

## Additional information

This works just fine on my PC. The issue is on mac.

**Comment by eric** [comment] 2020-07-02 18:28
I've noticed the only way to get a background webm video to animate is to set the text for the alert to an animation. I haven't been able to track down what is causing this to happen or if there is a trick with CSS or javascript to make it animate without that.

**Comment by PatTheMav** [comment] 2020-07-10 11:43
Possible duplicate of webm playback issue reported in https://github.com/obsproject/obs-browser/issues/213.

**Comment by jsinme** [comment] 2020-08-04 17:11
I am having the same issue with an mp4 file in a <video> tag.
Works fine on Windows.
On Mac, I have to be in the interact popup and constantly moving the mouse around on top of the video element in order for the stream to update. Audio plays fine.

**Comment by ryanfreng** [comment] 2020-08-06 15:19
This also is an issue for anything animated with css/html5. I have a countdown on a page that also doesn't change. It appears that the browser input just renders 1 frame and stops rendering.

**Comment by WizardCM** [comment] 2021-01-09 06:15
Thanks to the following PRs and the work of @PatTheMav and @pkviet - hardware acceleration is now available in OBS starting in [26.1.2](https://github.com/obsproject/obs-studio/releases/tag/26.1.2). This fixes rendering issues mentioned.

* #252
* https://github.com/obsproject/obs-studio/pull/3933
* https://github.com/obsproject/obs-studio/pull/3934
* https://github.com/obsproject/obs-studio/pull/4034

**Closed by WizardCM** 2021-01-09 06:15 UTC
